require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Metrics/AbcSize:
  Exclude:
    - "db/**/*"
Metrics/MethodLength:
  Exclude:
    - "db/**/*"
Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "lib/tasks/*"
Layout/LineLength:
  Exclude:
    - "config/initializers/*"
